# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/matching_separable_simuls',
                'doc_host': 'https://bsalanie.github.io',
                'git_url': 'https://github.com/bsalanie/matching_separable_simuls',
                'lib_path': 'matching_separable_simuls'},
  'syms': { 'matching_separable_simuls.index': {},
            'matching_separable_simuls.read_data': { 'matching_separable_simuls.read_data.get_root_dir': ( 'read_data.html#get_root_dir',
                                                                                                           'matching_separable_simuls/read_data.py'),
                                                     'matching_separable_simuls.read_data.normalize_mus': ( 'read_data.html#normalize_mus',
                                                                                                            'matching_separable_simuls/read_data.py'),
                                                     'matching_separable_simuls.read_data.read_margins': ( 'read_data.html#read_margins',
                                                                                                           'matching_separable_simuls/read_data.py'),
                                                     'matching_separable_simuls.read_data.read_marriages': ( 'read_data.html#read_marriages',
                                                                                                             'matching_separable_simuls/read_data.py'),
                                                     'matching_separable_simuls.read_data.reshape_varcov': ( 'read_data.html#reshape_varcov',
                                                                                                             'matching_separable_simuls/read_data.py')}}}
