# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/matching_separable_simuls',
                'doc_host': 'https://bsalanie.github.io',
                'git_url': 'https://github.com/bsalanie/matching_separable_simuls',
                'lib_path': 'matching_separable_simuls'},
  'syms': { 'matching_separable_simuls.core': { 'matching_separable_simuls.core.foo': ( 'core.html#foo',
                                                                                        'matching_separable_simuls/core.py')},
            'matching_separable_simuls.read_data': { 'matching_separable_simuls.read_data.read_margins': ( 'read_data.html#read_margins',
                                                                                                           'matching_separable_simuls/read_data.py'),
                                                     'matching_separable_simuls.read_data.read_marriages': ( 'read_data.html#read_marriages',
                                                                                                             'matching_separable_simuls/read_data.py')}}}