# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/index.ipynb.

# %% auto 0
__all__ = ['nx', 'my', 'muxy', 'varmus', 'ncat_men', 'ncat_women', 'mux0', 'mu0y']

# %% ../nbs/index.ipynb 10
#| echo: false
nx, my = read_margins(data_dir)
muxy, varmus = read_marriages(data_dir)
ncat_men, ncat_women = muxy.shape
mux0, mu0y = _get_singles(muxy, nx, my)
print(f"\nThe data has {ncat_men} types of men and {ncat_women} types of women.")
