# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_read_data.ipynb.

# %% auto 0
__all__ = ['data_dir', 'nx', 'my', 'muxy', 'varmus', 'read_margins', 'read_marriages']

# %% ../nbs/00_read_data.ipynb 4
data_dir = Path.cwd().parent / "matching_separable_simuls" / "ChooSiow70nNdata"

def read_margins(
    ) -> tuple[np.ndarray, np.ndarray]: 
    """reads and returns the margins for men and for women """
    nx = np.loadtxt(data_dir / "nx70n.txt")
    my = np.loadtxt(data_dir / "my70n.txt")
    return nx, my

def read_marriages(
    ) -> tuple[np.ndarray, np.ndarray]: 
    """ reads and returns the marriages and the variances"""
    muxy = np.loadtxt(data_dir / "muxy70nN.txt")
    varmus = np.loadtxt(data_dir / "varmus70nN.txt")
    return muxy, varmus

nx, my = read_margins()
muxy, varmus = read_marriages()
    

    
    
