# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_read_data.ipynb.

# %% auto 0
__all__ = ['get_root_dir', 'read_margins', 'read_marriages']

# %% ../nbs/00_read_data.ipynb 4
from fastcore.test import *
from sys import platform
import numpy as np
from pathlib import Path
from typing import Tuple

# %% ../nbs/00_read_data.ipynb 5
def get_root_dir(
) -> Path:
    """ returns the package directory """
    root_dir = Path.cwd().parent
    if platform in ["linux", "linux2"]:
        root_dir = Path.cwd().parent.parent
    return root_dir


# %% ../nbs/00_read_data.ipynb 6
def read_margins(
    data_dir: Path      # the data directory
    ) -> Tuple[np.ndarray, np.ndarray]: 
    """reads and returns the margins for men and for women """
    nx = np.loadtxt(data_dir / "nx70n.txt")
    my = np.loadtxt(data_dir / "my70n.txt")
    return nx, my

def read_marriages(
    data_dir: Path      # the data directory
    ) -> Tuple[np.ndarray, np.ndarray]: 
    """ reads and returns the marriages and the variances"""
    muxy = np.loadtxt(data_dir / "muxy70nN.txt")
    varmus = np.loadtxt(data_dir / "varmus70nN.txt")
    return muxy, varmus


    

    
    
